spring:
  data:
    elasticsearch:
      cluster-name: ${mall.elasticsearch.cluster-name}
      cluster-nodes: ${mall.elasticsearch.cluster-nodes}
      repositories:
        enabled: true

mall:
  swagger:
    enabled: true
    title: 日志中心
    description: 日志中心接口文档
    version: 1.0
    base-package: com.mallplus.log.controller