spring:
  datasource:
    url: jdbc:mysql://${mall.datasource.ip}:3306/mallcloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${mall.datasource.username}
    password: ${mall.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mallplus.ums.entity
  global-config:
    db-config:
      id-type: auto

mall:
  swagger:
    enabled: true
    title: 会员中心
    description: 会员中心接口文档
    version: 1.0
    base-package: com.mallplus.ums.controller
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800

authCode:
    expire:
        seconds: 90
redis:
    key:
        prefix:
            authCode: 'portal:authCode:'
            orderId: 'portal:orderId:'

wx:
    appId: wx15d4269d3210863d
    certName: /cert/apiclient_cert.p12
    getCode: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
    mchId: ''
    notifyUrl: http://localhost:8085/api/pay/notify
    orderquery: https://api.mch.weixin.qq.com/pay/orderquery
    paySignKey: ''
    refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
    refundqueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
    secret: 661e82bcf46dbe6c203c9f2f91d8937d
    templateId: nAt_DYLLwYXkIhtDb5nyEm0ynrt98OK3Z3MmeUooPz4
    tradeType: JSAPI
    uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    userMessage: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
    webAccessTokenhttps: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code

aliyun:
    oss:
        accessKeyId: test
        accessKeySecret: test
        bucketName: zscat-oss
        callback: http://localhost:8080/aliyun/oss/callback
        dir:
            prefix: mall/images/
        endpoint: oss-cn-shenzhen.aliyuncs.com
        maxSize: 10
        policy:
            expire: 300
    sms:
        accessKeyId: 5Jii89BFukxmun5j
        accessKeySecret: JvE9FcILlHu5gClmAJr89ZkEv00l9s
        day-count: 5
        expire-minute: 1
        sign:
            name: 京怡君商贸
        template:
            code: SMS_164240312
jwt:
    expiration: 604800
    secret: mySecret
    tokenHead: 'Bearer '
    tokenHeader: Authorization
